Traceback (most recent call last):
  File "c:\users\srinu\desktop\python\11_debugging\chapter_examples.py", line 29, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
